### ISSUE TITLE
Position-simulator -> status 500 reading RemotePositionMicroserviceCalls

### ISSUE THREAD

**Issue by MatteoMori** [DickChesterwood/istio-fleetman#29]
Hello All,

apologies for the this issue but I am having some troubles running the *warmup* exercise.

All, application's pods come up correctly but the `position-simulator` does not seems to work. By checking the logs it is firing the following error:

```
2020-01-08 13:56:55.871 ERROR 1 --- [   scheduling-1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task.

feign.FeignException$ServiceUnavailable: status 503 reading RemotePositionMicroserviceCalls#sendNewPositionReport(VehiclePosition)
	at feign.FeignException.errorStatus(FeignException.java:120) ~[feign-core-10.2.3.jar!/:na]
	at feign.FeignException.errorStatus(FeignException.java:86) ~[feign-core-10.2.3.jar!/:na]
	at feign.codec.ErrorDecoder$Default.decode(ErrorDecoder.java:93) ~[feign-core-10.2.3.jar!/:na]
	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:149) ~[feign-core-10.2.3.jar!/:na]
	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:78) ~[feign-core-10.2.3.jar!/:na]
	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:103) ~[feign-core-10.2.3.jar!/:na]
	at com.sun.proxy.$Proxy58.sendNewPositionReport(Unknown Source) ~[na:na]
	at com.virtualpairprogrammers.simulator.services.PositionTrackerExternalService.sendReportToPositionTracker(PositionTrackerExternalService.java:18) ~[classes!/:0.0.1-SNAPSHOT]
	at com.virtualpairprogrammers.simulator.journey.JourneySimulator.randomPositionUpdate(JourneySimulator.java:110) ~[classes!/:0.0.1-SNAPSHOT]
	at sun.reflect.GeneratedMethodAccessor28.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_131]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-5.1.9.RELEASE.jar!/:5.1.9.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_131]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_131]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_131]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]
```

**My env:**
* `minikube`
    * version: v1.6.2
    * minikube startup: `minikube start --memory='6000' --vm-driver=virtualbox`
* Repository:
    * tag: 6

do you have any idea why?

kind regards,
Matteo

**Comment by DickChesterwood** [comment]
Sorry I never saw this - I thought github sent notifications of new issues, seems not. Udemy Q&A is definitely the best place to get help.

I assume by now this will have gone away, it looks troubling though as the images should work out of the box. I hope it was something minor!
