### ISSUE TITLE
just deployed app without istio and when accessing it from browser on nodeport it is giving 500 error

### ISSUE THREAD

**Issue by nitinkansal1984** [DickChesterwood/istio-fleetman#31]
Error code 500 occured. fleetman-position-tracker.default.svc.cluster.local executing GET http://fleetman-position-tracker.default.svc.cluster.local:8080/vehicles/City%20Truck

Please help

**Comment by nitinkansal1984** [comment]
I could see below errors in position-tracker pod logs
2020-03-14 21:09:16.332 ERROR 1 --- [nio-8080-exec-5] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is feign.RetryableException: fleetman-staff-service.default.svc.cluster.local executing POST http://fleetman-staff-service.default.svc.cluster.local:8080/driver/Village%20Truck/11.6068828140000906872] with root cause

java.net.UnknownHostException: fleetman-staff-service.default.svc.cluster.local
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184) ~[na:1.8.0_131]
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_131]
        at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_131]
        at sun.net.NetworkClient.doConnect(NetworkClient.java:175) ~[na:1.8.0_131]
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:463) ~[na:1.8.0_131]
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:558) ~[na:1.8.0_131]
        at sun.net.www.http.HttpClient.<init>(HttpClient.java:242) ~[na:1.8.0_131]
        at sun.net.www.http.HttpClient.New(HttpClient.java:339) ~[na:1.8.0_131]
        at sun.net.www.http.HttpClient.New(HttpClient.java:357) ~[na:1.8.0_131]

**Comment by nitinkansal1984** [comment]
I was deploying application in appns namespace. But when I deployed application in default namespace, it started working like a charm.

**Comment by DickChesterwood** [comment]
Hi, sorry I missed this, didn't get a notification. 

It's because of my bad coding really. The system originated from the original kubernetes course, and to demonstrate fully qualified domain names, I used the following for the lookup:

fleetman-staff-service.default.svc.cluster.local

For that reason (notice the "default" in the domain name), you need to deploy to the default namespace.

Of course I could and should have just used "fleetman-staff-service" and then as long as it's all in the same namespace all would have been well.

Sorry about that, as I say it's a legacy as a result of an old demo that I should have tuned up before recording this course.

**Comment by nitinkansal1984** [comment]
It's really good to hear from you. I hope you are doing good. I really
liked and enjoyed and learning this course on istio.

You explained everything in much detail. It really helped me a lot.

I have gone through entire course two times
 I request you to add few more content.
